name: run python tests

on: [ push ]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.8, 3.9 ]
        installer: ["", "wheel"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest ${{ matrix.installer }}
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      - name: install package
        run: python -m pip install --use-feature=in-tree-build .
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: add aws certificates for thing
        run: |
          mkdir tests/certs
          ls tests/certs
          'echo "$AWS_ROOT_CA" > tests/certs/root-ca.pem'
          'echo "$AWS_THING_CERTIFICATE" > tests/certs/id-certificate.pem.crt'
          'echo "$AWS_THING_PRIVATE_KEY" > tests/certs/id-private.pem.key'
          'echo "$AWS_TEST_THING_CONFIG" > tests/certs/config.json'
        env:
          AWS_ROOT_CA: ${{ secrets.AWS_ROOT_CA }}
          AWS_THING_CERTIFICATE: ${{ secrets.AWS_THING_CERTIFICATE }}
          AWS_THING_PRIVATE_KEY: ${{ secrets.AWS_THING_PRIVATE_KEY }}
          AWS_TEST_THING_CONFIG: ${{ secrets.AWS_TEST_THING_CONFIG }}
      - name: test with pytest
        run: pytest